In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = {
    'student_id':  [1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name':        ['Alice', 'Bob', 'Bob', 'Cara', None, 'Eve', 
                    'frank', 'Grace', 'HENRY', 'ivy', 'Jack'],
    'age':         [17, 18, 18, 16, 19, None, 17, 25, 16, 18, 17],
    'math':        [85, 90, 90, 78, 110, 65, 72, 88, None, 91, 55],
    'english':     [78, 85, 85, None, 70, 88, 65, 91, 77, 85, 60],
    'science':     [90, 88, 88, 82, 75, 79, 68, 95, 83, 78, 62],
    'class':       ['A', 'B', 'B', 'A', 'C', 'B', 'a', 'C', 'A', 'B', 'C'],
    'join_date':   ['2023-09-01', '2023-09-01', '2023-09-01', '2023-09-15',
                    '2023-09-01', '2023-09-15', '2023-09-01', '2023-09-01',
                    '2023-09-15', '2023-09-01', '2023-09-01']
}


df = pd.DataFrame(raw_data)
df

    student_id   name   age   math  english  science class   join_date
0            1  Alice  17.0   85.0     78.0       90     A  2023-09-01
1            2    Bob  18.0   90.0     85.0       88     B  2023-09-01
2            2    Bob  18.0   90.0     85.0       88     B  2023-09-01
3            3   Cara  16.0   78.0      NaN       82     A  2023-09-15
4            4   None  19.0  110.0     70.0       75     C  2023-09-01
5            5    Eve   NaN   65.0     88.0       79     B  2023-09-15
6            6  frank  17.0   72.0     65.0       68     a  2023-09-01
7            7  Grace  25.0   88.0     91.0       95     C  2023-09-01
8            8  HENRY  16.0    NaN     77.0       83     A  2023-09-15
9            9    ivy  18.0   91.0     85.0       78     B  2023-09-01
10          10   Jack  17.0   55.0     60.0       62     C  2023-09-01

In [3]:
# assess the data

def assess_data(df):
    print(f'the shape', {df.shape})
    print(f'\n --- the data info ---')
    print(df.info())
    print(f'\n --- the data types ---')
    print(df.dtypes)
    print(f'\n --- missing vales ---')
    print(df.isnull().sum())
    print(f' --- data statistics ---')
    print(df.describe())
    print(f'\n --- unique values per columns ---')
    for col in df.columns:
        print(f' {col}: {df[col].nunique()} unique - {df[col].unique()[: 5]}')


assess_data(df)

the shape {(11, 8)}

 --- the data info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  11 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     float64
 3   math        10 non-null     float64
 4   english     10 non-null     float64
 5   science     11 non-null     int64
 6   class       11 non-null     object
 7   join_date   11 non-null     object
dtypes: float64(3), int64(2), object(3)
memory usage: 836.0+ bytes
None

 --- the data types ---
student_id      int64
name           object
age           float64
math          float64
english       float64
science         int64
class          object
join_date      object
dtype: object

 --- missing vales ---
student_id    0
name          1
age           1
math          1
english       1
science       0
class         0
join_date     0
dtype: int64
 --- data statistics ---
       student_id        age        math    english    science
count   11.000000  10.000000   10.000000  10.000000  11.000000
mean     5.181818  18.100000   82.400000  78.400000  80.727273
std      3.060006   2.601282   15.529184  10.394443   9.788676
min      1.000000  16.000000   55.000000  60.000000  62.000000
25%      2.500000  17.000000   73.500000  71.750000  76.500000
50%      5.000000  17.500000   86.500000  81.500000  82.000000
75%      7.500000  18.000000   90.000000  85.000000  88.000000
max     10.000000  25.000000  110.000000  91.000000  95.000000

 --- unique values per columns ---
 student_id: 10 unique - [1 2 3 4 5]
 name: 9 unique - ['Alice' 'Bob' 'Cara' None 'Eve']
 age: 5 unique - [17. 18. 16. 19. nan]
 math: 9 unique - [ 85.  90.  78. 110.  65.]
 english: 8 unique - [78. 85. nan 70. 88.]
 science: 10 unique - [90 88 82 75 79]
 class: 4 unique - ['A' 'B' 'C' 'a']
 join_date: 2 unique - ['2023-09-01' '2023-09-15']

In [4]:
# find Duplicates

df[df.duplicated()]

   student_id name   age  math  english  science class   join_date
2           2  Bob  18.0  90.0     85.0       88     B  2023-09-01

In [5]:
df[df.duplicated(keep = False)]

   student_id name   age  math  english  science class   join_date
1           2  Bob  18.0  90.0     85.0       88     B  2023-09-01
2           2  Bob  18.0  90.0     85.0       88     B  2023-09-01

In [6]:
# remove duplicates

df = df.drop_duplicates()
df

    student_id   name   age   math  english  science class   join_date
0            1  Alice  17.0   85.0     78.0       90     A  2023-09-01
1            2    Bob  18.0   90.0     85.0       88     B  2023-09-01
3            3   Cara  16.0   78.0      NaN       82     A  2023-09-15
4            4   None  19.0  110.0     70.0       75     C  2023-09-01
5            5    Eve   NaN   65.0     88.0       79     B  2023-09-15
6            6  frank  17.0   72.0     65.0       68     a  2023-09-01
7            7  Grace  25.0   88.0     91.0       95     C  2023-09-01
8            8  HENRY  16.0    NaN     77.0       83     A  2023-09-15
9            9    ivy  18.0   91.0     85.0       78     B  2023-09-01
10          10   Jack  17.0   55.0     60.0       62     C  2023-09-01

In [7]:
# df.drop_duplicates(subset = ['student_id'])

In [8]:
df = df.reset_index(drop = True)

df

   student_id   name   age   math  english  science class   join_date
0           1  Alice  17.0   85.0     78.0       90     A  2023-09-01
1           2    Bob  18.0   90.0     85.0       88     B  2023-09-01
2           3   Cara  16.0   78.0      NaN       82     A  2023-09-15
3           4   None  19.0  110.0     70.0       75     C  2023-09-01
4           5    Eve   NaN   65.0     88.0       79     B  2023-09-15
5           6  frank  17.0   72.0     65.0       68     a  2023-09-01
6           7  Grace  25.0   88.0     91.0       95     C  2023-09-01
7           8  HENRY  16.0    NaN     77.0       83     A  2023-09-15
8           9    ivy  18.0   91.0     85.0       78     B  2023-09-01
9          10   Jack  17.0   55.0     60.0       62     C  2023-09-01

In [9]:
# fixing data types

df['join_date'] = pd.to_datetime(df['join_date'])
df['join_date']

0   2023-09-01
1   2023-09-01
2   2023-09-15
3   2023-09-01
4   2023-09-15
5   2023-09-01
6   2023-09-01
7   2023-09-15
8   2023-09-01
9   2023-09-01
Name: join_date, dtype: datetime64[ns]

In [10]:
# join month

df['join_month'] = df['join_date'].dt.month
df

,student_id,name,age,math,english,science,class,join_date,join_month
0,1,Alice,17.0,85.0,78.0,90,A,2023-09-01,9
1,2,Bob,18.0,90.0,85.0,88,B,2023-09-01,9
2,3,Cara,16.0,78.0,NaN,82,A,2023-09-15,9
3,4,None,19.0,110.0,70.0,75,C,2023-09-01,9
4,5,Eve,NaN,65.0,88.0,79,B,2023-09-15,9
5,6,frank,17.0,72.0,65.0,68,a,2023-09-01,9
6,7,Grace,25.0,88.0,91.0,95,C,2023-09-01,9
7,8,HENRY,16.0,NaN,77.0,83,A,2023-09-15,9
8,9,ivy,18.0,91.0,85.0,78,B,2023-09-01,9
9,10,Jack,17.0,55.0,60.0,62,C,2023-09-01,9

In [11]:
df['join_day'] = df['join_date'].dt.day_of_week
df['join_day']

0    4
1    4
2    4
3    4
4    4
5    4
6    4
7    4
8    4
9    4
Name: join_day, dtype: int32

In [12]:
df.dtypes

student_id             int64
name                  object
age                  float64
math                 float64
english              float64
science                int64
class                 object
join_date     datetime64[ns]
join_month             int32
join_day               int32
dtype: object

In [13]:
df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,A,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,B,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,A,2023-09-15,9,4
3,4,None,19.0,110.0,70.0,75,C,2023-09-01,9,4
4,5,Eve,NaN,65.0,88.0,79,B,2023-09-15,9,4
5,6,frank,17.0,72.0,65.0,68,a,2023-09-01,9,4
6,7,Grace,25.0,88.0,91.0,95,C,2023-09-01,9,4
7,8,HENRY,16.0,NaN,77.0,83,A,2023-09-15,9,4
8,9,ivy,18.0,91.0,85.0,78,B,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,C,2023-09-01,9,4

In [14]:
# standardized formatting

df['name'] = df['name'].str.title()

df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,A,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,B,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,A,2023-09-15,9,4
3,4,None,19.0,110.0,70.0,75,C,2023-09-01,9,4
4,5,Eve,NaN,65.0,88.0,79,B,2023-09-15,9,4
5,6,Frank,17.0,72.0,65.0,68,a,2023-09-01,9,4
6,7,Grace,25.0,88.0,91.0,95,C,2023-09-01,9,4
7,8,Henry,16.0,NaN,77.0,83,A,2023-09-15,9,4
8,9,Ivy,18.0,91.0,85.0,78,B,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,C,2023-09-01,9,4

In [15]:
df['class'] = df['class'].str.upper()

df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,A,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,B,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,A,2023-09-15,9,4
3,4,None,19.0,110.0,70.0,75,C,2023-09-01,9,4
4,5,Eve,NaN,65.0,88.0,79,B,2023-09-15,9,4
5,6,Frank,17.0,72.0,65.0,68,A,2023-09-01,9,4
6,7,Grace,25.0,88.0,91.0,95,C,2023-09-01,9,4
7,8,Henry,16.0,NaN,77.0,83,A,2023-09-15,9,4
8,9,Ivy,18.0,91.0,85.0,78,B,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,C,2023-09-01,9,4

In [16]:
df['name'] = df['name'].str.strip()
df['class'] = df['name'].str.strip()

In [17]:
df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,Cara,2023-09-15,9,4
3,4,None,19.0,110.0,70.0,75,None,2023-09-01,9,4
4,5,Eve,NaN,65.0,88.0,79,Eve,2023-09-15,9,4
5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
6,7,Grace,25.0,88.0,91.0,95,Grace,2023-09-01,9,4
7,8,Henry,16.0,NaN,77.0,83,Henry,2023-09-15,9,4
8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [19]:
# removing impossible value in math column 
# domain knowledge tells you score cannot be more than 100

df.loc[df['math'] > 100, 'math'] = np.nan

df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,Cara,2023-09-15,9,4
3,4,None,19.0,NaN,70.0,75,None,2023-09-01,9,4
4,5,Eve,NaN,65.0,88.0,79,Eve,2023-09-15,9,4
5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
6,7,Grace,25.0,88.0,91.0,95,Grace,2023-09-01,9,4
7,8,Henry,16.0,NaN,77.0,83,Henry,2023-09-15,9,4
8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [21]:
# remove outliers

def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[column] >= lower) & (df[column] <= upper)]

df = remove_outliers_iqr(df, 'age')
df

,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,3,Cara,16.0,78.0,NaN,82,Cara,2023-09-15,9,4
3,4,None,19.0,NaN,70.0,75,None,2023-09-01,9,4
5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
7,8,Henry,16.0,NaN,77.0,83,Henry,2023-09-15,9,4
8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [27]:
df = df.reset_index()

df

,index,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,2,3,Cara,16.0,78.0,NaN,82,Cara,2023-09-15,9,4
3,3,4,None,19.0,NaN,70.0,75,None,2023-09-01,9,4
4,5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
5,7,8,Henry,16.0,NaN,77.0,83,Henry,2023-09-15,9,4
6,8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
7,9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [29]:
df.isnull().mean()*100

index          0.0
student_id     0.0
name          12.5
age            0.0
math          25.0
english       12.5
science        0.0
class         12.5
join_date      0.0
join_month     0.0
join_day       0.0
dtype: float64

In [30]:
df.isnull().sum()

index         0
student_id    0
name          1
age           0
math          2
english       1
science       0
class         1
join_date     0
join_month    0
join_day      0
dtype: int64

In [32]:
# Handle missing values

df = df.dropna(thresh = 5)
df

,index,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,2,3,Cara,16.0,78.0,NaN,82,Cara,2023-09-15,9,4
3,3,4,None,19.0,NaN,70.0,75,None,2023-09-01,9,4
4,5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
5,7,8,Henry,16.0,NaN,77.0,83,Henry,2023-09-15,9,4
6,8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
7,9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [37]:
# fill numerical with median

df['math'] = df['math'].fillna(df['math'].median())

In [38]:
df['english'] = df['english'].fillna(df['english'].median())

df

,index,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,2,3,Cara,16.0,78.0,77.0,82,Cara,2023-09-15,9,4
3,3,4,None,19.0,81.5,70.0,75,None,2023-09-01,9,4
4,5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
5,7,8,Henry,16.0,81.5,77.0,83,Henry,2023-09-15,9,4
6,8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
7,9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [42]:
df['name'] = df['name'].fillna(df['name'].mode()[0])

df

,index,student_id,name,age,math,english,science,class,join_date,join_month,join_day
0,0,1,Alice,17.0,85.0,78.0,90,Alice,2023-09-01,9,4
1,1,2,Bob,18.0,90.0,85.0,88,Bob,2023-09-01,9,4
2,2,3,Cara,16.0,78.0,77.0,82,Cara,2023-09-15,9,4
3,3,4,Alice,19.0,81.5,70.0,75,None,2023-09-01,9,4
4,5,6,Frank,17.0,72.0,65.0,68,Frank,2023-09-01,9,4
5,7,8,Henry,16.0,81.5,77.0,83,Henry,2023-09-15,9,4
6,8,9,Ivy,18.0,91.0,85.0,78,Ivy,2023-09-01,9,4
7,9,10,Jack,17.0,55.0,60.0,62,Jack,2023-09-01,9,4

In [ ]:
# there is forward fill

df['score'].ffill()

In [44]:
# Merging Data frame

students = pd.DataFrame({
    'student_id': [1,2,3,4,5],
    'name': ['alice', 'bob', 'cara', 'dan', 'eve'],
    'class_id': [101, 102, 101, 103, 102]
})


classes = pd.DataFrame({
    'class_id': [101, 102, 103],
    'class_name': ['maths', 'science', 'history'],
    'teacher': ['mr. adams', 'ms. brown', 'mr. clark']
})

scores = pd.DataFrame({
    'student_id': [1,2,3,5,6],
    'score': [85, 90, 78, 88, 92]
})

In [45]:
# INNER JOIN

pd.merge(students, scores, on = 'student_id', how = 'inner')

   student_id   name  class_id  score
0           1  alice       101     85
1           2    bob       102     90
2           3   cara       101     78
3           5    eve       102     88

In [46]:
pd.merge(students, scores, on = 'student_id', how = 'right')

   student_id   name  class_id  score
0           1  alice     101.0     85
1           2    bob     102.0     90
2           3   cara     101.0     78
3           5    eve     102.0     88
4           6    NaN       NaN     92

In [47]:
pd.merge(students, scores, on = 'student_id', how = 'left')

   student_id   name  class_id  score
0           1  alice       101   85.0
1           2    bob       102   90.0
2           3   cara       101   78.0
3           4    dan       103    NaN
4           5    eve       102   88.0

In [48]:
pd.merge(students, scores, on = 'student_id', how = 'outer')

   student_id   name  class_id  score
0           1  alice     101.0   85.0
1           2    bob     102.0   90.0
2           3   cara     101.0   78.0
3           4    dan     103.0    NaN
4           5    eve     102.0   88.0
5           6    NaN       NaN   92.0

In [50]:
# merging on different column names

pd.merge(students, classes, left_on = 'class_id', right_on = 'class_id')

   student_id   name  class_id class_name    teacher
0           1  alice       101      maths  mr. adams
1           2    bob       102    science  ms. brown
2           3   cara       101      maths  mr. adams
3           4    dan       103    history  mr. clark
4           5    eve       102    science  ms. brown

In [55]:
# chaining multiple merges

full_df = (students
    .merge(classes, on = 'class_id')
    .merge(scores, on = 'student_id', how = 'left'))

full_df

   student_id   name  class_id class_name    teacher  score
0           1  alice       101      maths  mr. adams   85.0
1           2    bob       102    science  ms. brown   90.0
2           3   cara       101      maths  mr. adams   78.0
3           4    dan       103    history  mr. clark    NaN
4           5    eve       102    science  ms. brown   88.0

CODING EXERCISE ON PANDAS

In [2]:
dirty_df = pd.DataFrame({
    'id':      [1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name':    ['Alice', 'Bob', 'Bob', 'cara', None, 'eve', 
                'Frank', 'grace', 'HENRY', 'Ivy', 'jack'],
    'age':     [17, 18, 18, 16, 19, None, 17, 30, 16, 18, 17],
    'score':   [85, 90, 90, 78, 105, 65, 72, 88, None, 91, 55],
    'grade':   ['B', 'A', 'A', 'B', 'A', 'C', 'b', 'A', 'B', 'A', 'C'],
    'city':    ['Lagos', 'Abuja', 'Abuja', 'Lagos', 'Kano', 
                'Lagos', 'Abuja', 'Kano', 'Lagos', 'Abuja', 'Kano']
})

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
2    2    Bob  18.0   90.0     A  Abuja
3    3   cara  16.0   78.0     B  Lagos
4    4   None  19.0  105.0     A   Kano
5    5    eve   NaN   65.0     C  Lagos
6    6  Frank  17.0   72.0     b  Abuja
7    7  grace  30.0   88.0     A   Kano
8    8  HENRY  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   jack  17.0   55.0     C   Kano

In [3]:
# assess the dataset

def assess_dataset(dirty_df):
    print(f'shape of dataset', (dirty_df.shape)),
    print(f'\n --- the data type of the dataset ---')
    print(dirty_df.dtypes)
    print(f'\n --- missing values ---')
    print(dirty_df.isnull().sum())
    print(f'\n --- unique values ---')
    for col in dirty_df.columns:
        print(f' {col}: {dirty_df[col].nunique()} unique - {dirty_df[col].unique()[:5]}')

assess_dataset(dirty_df)

shape of dataset (11, 6)

 --- the data type of the dataset ---
id         int64
name      object
age      float64
score    float64
grade     object
city      object
dtype: object

 --- missing values ---
id       0
name     1
age      1
score    1
grade    0
city     0
dtype: int64

 --- unique values ---
 id: 10 unique - [1 2 3 4 5]
 name: 9 unique - ['Alice' 'Bob' 'cara' None 'eve']
 age: 5 unique - [17. 18. 16. 19. nan]
 score: 9 unique - [ 85.  90.  78. 105.  65.]
 grade: 4 unique - ['B' 'A' 'C' 'b']
 city: 3 unique - ['Lagos' 'Abuja' 'Kano']

In [4]:
# Exercise 2
# Clean the dataset in this order:


# - Remove duplicate rows

dirty_df[dirty_df.duplicated(keep = False)]

   id name   age  score grade   city
1   2  Bob  18.0   90.0     A  Abuja
2   2  Bob  18.0   90.0     A  Abuja

In [5]:
dirty_df.drop_duplicates(inplace = True)

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
3    3   cara  16.0   78.0     B  Lagos
4    4   None  19.0  105.0     A   Kano
5    5    eve   NaN   65.0     C  Lagos
6    6  Frank  17.0   72.0     b  Abuja
7    7  grace  30.0   88.0     A   Kano
8    8  HENRY  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   jack  17.0   55.0     C   Kano

In [6]:
# - Fix name capitalization

dirty_df['name'] = dirty_df['name'].str.title()

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
3    3   Cara  16.0   78.0     B  Lagos
4    4   None  19.0  105.0     A   Kano
5    5    Eve   NaN   65.0     C  Lagos
6    6  Frank  17.0   72.0     b  Abuja
7    7  Grace  30.0   88.0     A   Kano
8    8  Henry  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   Jack  17.0   55.0     C   Kano

In [158]:
# - Fix grade capitalization

dirty_df['grade'] = dirty_df['grade'].str.upper()

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
3    3   Cara  16.0   78.0     B  Lagos
4    4   None  19.0  105.0     A   Kano
5    5    Eve   NaN   65.0     C  Lagos
6    6  Frank  17.0   72.0     B  Abuja
7    7  Grace  30.0   88.0     A   Kano
8    8  Henry  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   Jack  17.0   55.0     C   Kano

In [159]:
# - Replace impossible score (>100) with NaN

dirty_df.loc[dirty_df['score'] > 100, 'score'] = np.nan

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
3    3   Cara  16.0   78.0     B  Lagos
4    4   None  19.0    NaN     A   Kano
5    5    Eve   NaN   65.0     C  Lagos
6    6  Frank  17.0   72.0     B  Abuja
7    7  Grace  30.0   88.0     A   Kano
8    8  Henry  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   Jack  17.0   55.0     C   Kano

In [160]:
# - Remove age outlier (anyone over 25 is an error in this school dataset)

def remove_outlier(dirty_df, columns):
    Q1 = dirty_df[columns].quantile(0.25)
    Q3 = dirty_df[columns].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return dirty_df[(dirty_df[columns] >= lower) & (dirty_df[columns] <= upper)]

dirty_df = remove_outlier(dirty_df, 'age')

dirty_df

    id   name   age  score grade   city
0    1  Alice  17.0   85.0     B  Lagos
1    2    Bob  18.0   90.0     A  Abuja
3    3   Cara  16.0   78.0     B  Lagos
4    4   None  19.0    NaN     A   Kano
6    6  Frank  17.0   72.0     B  Abuja
8    8  Henry  16.0    NaN     B  Lagos
9    9    Ivy  18.0   91.0     A  Abuja
10  10   Jack  17.0   55.0     C   Kano

In [169]:
# - Fill missing score with median


dirty_df['score'] = dirty_df['score'].fillna(dirty_df['score'].median())

dirty_df

   id     name   age  score grade   city
0   1    Alice  17.0   85.0     B  Lagos
1   2      Bob  18.0   90.0     A  Abuja
2   3     Cara  16.0   78.0     B  Lagos
3   4  Unknown  19.0   81.5     A   Kano
4   6    Frank  17.0   72.0     B  Abuja
5   8    Henry  16.0   81.5     B  Lagos
6   9      Ivy  18.0   91.0     A  Abuja
7  10     Jack  17.0   55.0     C   Kano

In [170]:
# - Fill missing name with 'Unknown'

dirty_df['name'] = dirty_df['name'].fillna('Unknown')

dirty_df

   id     name   age  score grade   city
0   1    Alice  17.0   85.0     B  Lagos
1   2      Bob  18.0   90.0     A  Abuja
2   3     Cara  16.0   78.0     B  Lagos
3   4  Unknown  19.0   81.5     A   Kano
4   6    Frank  17.0   72.0     B  Abuja
5   8    Henry  16.0   81.5     B  Lagos
6   9      Ivy  18.0   91.0     A  Abuja
7  10     Jack  17.0   55.0     C   Kano

In [171]:
# - Fill missing age with median age

dirty_df['age'].fillna(df['age'].median())

0    17.0
1    18.0
2    16.0
3    19.0
4    17.0
5    16.0
6    18.0
7    17.0
Name: age, dtype: float64

In [172]:
# - Reset the index

dirty_df = dirty_df.reset_index(drop = True)

In [173]:
dirty_df

   id     name   age  score grade   city
0   1    Alice  17.0   85.0     B  Lagos
1   2      Bob  18.0   90.0     A  Abuja
2   3     Cara  16.0   78.0     B  Lagos
3   4  Unknown  19.0   81.5     A   Kano
4   6    Frank  17.0   72.0     B  Abuja
5   8    Henry  16.0   81.5     B  Lagos
6   9      Ivy  18.0   91.0     A  Abuja
7  10     Jack  17.0   55.0     C   Kano

In [174]:
# Exercise 3
# After cleaning, using groupby find:
# - Average score per city

dirty_df.groupby('city')['score'].mean().round(2)

city
Abuja    84.33
Kano     68.25
Lagos    81.50
Name: score, dtype: float64

In [175]:
# - Number of students per grade

dirty_df.groupby('grade')['name'].count()

grade
A    3
B    4
C    1
Name: name, dtype: int64

In [181]:
# - City with the highest average score

city_avg = dirty_df.groupby('city')['score'].mean().round(2)

print(f' city with the highest average score: {city_avg.idxmax()} ({city_avg.max()})')
# abuja has the highest average per city with 84.33 score.

 city with the highest average score: Abuja (84.33)

In [7]:
# Exercise 4 — Merging

extra_info = pd.DataFrame({
    'id':      [1, 2, 3, 4, 5, 6, 12, 13],
    'subject': ['Math', 'Science', 'Math', 'History', 
                'Science', 'Math', 'Science', 'History'],
    'tutor':   ['Mr. A', 'Ms. B', 'Mr. A', 'Mr. C',
                'Ms. B', 'Mr. A', 'Ms. B', 'Mr. C']
})

extra_info

   id  subject  tutor
0   1     Math  Mr. A
1   2  Science  Ms. B
2   3     Math  Mr. A
3   4  History  Mr. C
4   5  Science  Ms. B
5   6     Math  Mr. A
6  12  Science  Ms. B
7  13  History  Mr. C

In [8]:
# Merge dirty_df (after cleaning) with extra_info

pd.merge(dirty_df, extra_info, on = 'id', how = 'inner')

   id   name   age  score grade   city  subject  tutor
0   1  Alice  17.0   85.0     B  Lagos     Math  Mr. A
1   2    Bob  18.0   90.0     A  Abuja  Science  Ms. B
2   3   Cara  16.0   78.0     B  Lagos     Math  Mr. A
3   4   None  19.0  105.0     A   Kano  History  Mr. C
4   5    Eve   NaN   65.0     C  Lagos  Science  Ms. B
5   6  Frank  17.0   72.0     b  Abuja     Math  Mr. A

In [9]:
# Use a left join — explain in a comment why left join is correct here

full_df = pd.merge(dirty_df, extra_info, on = 'id', how = 'left')

full_df
# left join is better here because it will select all value on dirty_df which contains important informations to match to the right to have complete data
# as against using other merge option which will lead to an incomplete data.

   id   name   age  score grade   city  subject  tutor
0   1  Alice  17.0   85.0     B  Lagos     Math  Mr. A
1   2    Bob  18.0   90.0     A  Abuja  Science  Ms. B
2   3   Cara  16.0   78.0     B  Lagos     Math  Mr. A
3   4   None  19.0  105.0     A   Kano  History  Mr. C
4   5    Eve   NaN   65.0     C  Lagos  Science  Ms. B
5   6  Frank  17.0   72.0     b  Abuja     Math  Mr. A
6   7  Grace  30.0   88.0     A   Kano      NaN    NaN
7   8  Henry  16.0    NaN     B  Lagos      NaN    NaN
8   9    Ivy  18.0   91.0     A  Abuja      NaN    NaN
9  10   Jack  17.0   55.0     C   Kano      NaN    NaN

In [10]:
# How many students have no tutor assigned? (NaN in tutor column after merge)

full_df.isnull().sum()


# from this, 3 students has no tutor

id         0
name       1
age        1
score      1
grade      0
city       0
subject    4
tutor      4
dtype: int64

Mini Project: Real Data Cleaning Pipeline

In [47]:
student = pd.DataFrame({
    'student_id': [1,2,3,4,5,6,7,8,9,10],
    'name':  ['alice','BOB','Cara','dan','EVE','frank',
              'Grace','HENRY','ivy','Jack'],
    'age':   [17, 18, 16, 19, 17, 18, 16, 15, 17, 18],
    'gender':['F','M','F','M','F','M','F','M','F','M'],
    'class_id': [101,102,101,103,102,101,103,102,101,103]
})

scores = pd.DataFrame({
    'student_id': [1,2,3,4,5,6,7,8,9,10,1,2],
    'subject':    ['Math','Math','Math','Math','Math',
                   'Math','Math','Math','Math','Math',
                   'Math','Math'],
    'score': [85, 90, 78, 110, 88, 72, 95, 65, 91, 55, 85, 90]
})


classes = pd.DataFrame({
    'class_id':   [101, 102, 103],
    'class_name': ['Alpha', 'Beta', 'Gamma'],
    'teacher':    ['Mr. Adams', 'Ms. Brown', 'Mr. Clark']
})

In [48]:
student

   student_id   name  age gender  class_id
0           1  alice   17      F       101
1           2    BOB   18      M       102
2           3   Cara   16      F       101
3           4    dan   19      M       103
4           5    EVE   17      F       102
5           6  frank   18      M       101
6           7  Grace   16      F       103
7           8  HENRY   15      M       102
8           9    ivy   17      F       101
9          10   Jack   18      M       103

In [49]:
scores

    student_id subject  score
0            1    Math     85
1            2    Math     90
2            3    Math     78
3            4    Math    110
4            5    Math     88
5            6    Math     72
6            7    Math     95
7            8    Math     65
8            9    Math     91
9           10    Math     55
10           1    Math     85
11           2    Math     90

In [50]:
classes

   class_id class_name    teacher
0       101      Alpha  Mr. Adams
1       102       Beta  Ms. Brown
2       103      Gamma  Mr. Clark

CLEAN EACH TABLE

In [51]:
# STUDENT TABLE

student

   student_id   name  age gender  class_id
0           1  alice   17      F       101
1           2    BOB   18      M       102
2           3   Cara   16      F       101
3           4    dan   19      M       103
4           5    EVE   17      F       102
5           6  frank   18      M       101
6           7  Grace   16      F       103
7           8  HENRY   15      M       102
8           9    ivy   17      F       101
9          10   Jack   18      M       103

In [52]:
def info_asses(student):
    print(f'\n --- the shape ---: {student.shape}')
    print(f'\ --- data types ---: {student.dtypes}')
    print(f'\n --- missing values ---: {student.isnull().sum()}')
    print(f'\n --- unique values ---')
    for col in student.columns:
        print(f' {col}: {student[col].nunique()} unique - {student[col].unique()[:5]}')

info_asses(student)

 --- the shape ---: (10, 5)
\ --- data types ---: student_id     int64
name          object
age            int64
gender        object
class_id       int64
dtype: object

 --- missing values ---: student_id    0
name          0
age           0
gender        0
class_id      0
dtype: int64

 --- unique values ---
 student_id: 10 unique - [1 2 3 4 5]
 name: 10 unique - ['alice' 'BOB' 'Cara' 'dan' 'EVE']
 age: 5 unique - [17 18 16 19 15]
 gender: 2 unique - ['F' 'M']
 class_id: 3 unique - [101 102 103]

In [53]:
# Your pipeline must:
# 1. Clean students table:
#    - Fix name capitalization

student['name'] = student['name'].str.title()

student

#    - Identify and note any age outliers (no removal needed, just flag them)

# note: no outlier on the age column

   student_id   name  age gender  class_id
0           1  Alice   17      F       101
1           2    Bob   18      M       102
2           3   Cara   16      F       101
3           4    Dan   19      M       103
4           5    Eve   17      F       102
5           6  Frank   18      M       101
6           7  Grace   16      F       103
7           8  Henry   15      M       102
8           9    Ivy   17      F       101
9          10   Jack   18      M       103

In [54]:
scores

    student_id subject  score
0            1    Math     85
1            2    Math     90
2            3    Math     78
3            4    Math    110
4            5    Math     88
5            6    Math     72
6            7    Math     95
7            8    Math     65
8            9    Math     91
9           10    Math     55
10           1    Math     85
11           2    Math     90

In [55]:
scores[scores.duplicated()]

    student_id subject  score
10           1    Math     85
11           2    Math     90

In [56]:
# 2. Clean scores table:
#    - Remove duplicate scores (same student, same subject)

scores.drop_duplicates(inplace = True)

scores

   student_id subject  score
0           1    Math     85
1           2    Math     90
2           3    Math     78
3           4    Math    110
4           5    Math     88
5           6    Math     72
6           7    Math     95
7           8    Math     65
8           9    Math     91
9          10    Math     55

In [57]:
#    - Replace impossible scores (>100) with NaN

scores.loc[scores['score'] > 100, 'score'] = np.nan

scores

   student_id subject  score
0           1    Math   85.0
1           2    Math   90.0
2           3    Math   78.0
3           4    Math    NaN
4           5    Math   88.0
5           6    Math   72.0
6           7    Math   95.0
7           8    Math   65.0
8           9    Math   91.0
9          10    Math   55.0

In [59]:
#    - Fill NaN scores with median

scores['score'] = scores['score'].fillna(scores['score'].median())

scores

   student_id subject  score
0           1    Math   85.0
1           2    Math   90.0
2           3    Math   78.0
3           4    Math   85.0
4           5    Math   88.0
5           6    Math   72.0
6           7    Math   95.0
7           8    Math   65.0
8           9    Math   91.0
9          10    Math   55.0

In [29]:
classes

   class_id class_name    teacher
0       101      Alpha  Mr. Adams
1       102       Beta  Ms. Brown
2       103      Gamma  Mr. Clark

In [61]:
# 3. Merge all three tables into one complete DataFrame called full_df
#    Students + Scores + Classes


full_df = (student
          .merge(classes, on = 'class_id' )
           .merge(scores, on = 'student_id', how = 'left')
          )

full_df

#    Use appropriate join types and explain your choices in comments

# i used left join because it will collect all student data and match it with the other necesary data which is what is needed.

,student_id,name,age,gender,class_id,class_name,teacher,subject,score
0,1,Alice,17,F,101,Alpha,Mr. Adams,Math,85.0
1,2,Bob,18,M,102,Beta,Ms. Brown,Math,90.0
2,3,Cara,16,F,101,Alpha,Mr. Adams,Math,78.0
3,4,Dan,19,M,103,Gamma,Mr. Clark,Math,85.0
4,5,Eve,17,F,102,Beta,Ms. Brown,Math,88.0
5,6,Frank,18,M,101,Alpha,Mr. Adams,Math,72.0
6,7,Grace,16,F,103,Gamma,Mr. Clark,Math,95.0
7,8,Henry,15,M,102,Beta,Ms. Brown,Math,65.0
8,9,Ivy,17,F,101,Alpha,Mr. Adams,Math,91.0
9,10,Jack,18,M,103,Gamma,Mr. Clark,Math,55.0

In [62]:
# 4. Analysis on full_df:
#    - Average score per class

full_df.groupby('class_name')['score'].mean()

class_name
Alpha    81.500000
Beta     81.000000
Gamma    78.333333
Name: score, dtype: float64

In [76]:
#    - Top student per class

idx = full_df.groupby('class_name')['score'].idxmax()

full_df.loc[idx, ['class_name', 'name', 'score' ]]

  class_name   name  score
8      Alpha    Ivy   91.0
1       Beta    Bob   90.0
6      Gamma  Grace   95.0

In [64]:
#    - Gender breakdown of scores


full_df.groupby('gender')['score'].mean()

gender
F    87.4
M    73.4
Name: score, dtype: float64

In [73]:
# lowest score by gender

full_df.groupby('gender')['score'].min()

gender
F    78.0
M    55.0
Name: score, dtype: float64

In [77]:
# best score by gender

best_by_gender = full_df.groupby('gender')['score'].max()

print(f' best student by gender\n {best_by_gender}')

 best student by gender
 gender
F    95.0
M    90.0
Name: score, dtype: float64

In [72]:
#  student average score by teacher 

full_df.groupby('teacher')['score'].mean()

teacher
Mr. Adams    81.500000
Mr. Clark    78.333333
Ms. Brown    81.000000
Name: score, dtype: float64

In [68]:
full_df

,student_id,name,age,gender,class_id,class_name,teacher,subject,score
0,1,Alice,17,F,101,Alpha,Mr. Adams,Math,85.0
1,2,Bob,18,M,102,Beta,Ms. Brown,Math,90.0
2,3,Cara,16,F,101,Alpha,Mr. Adams,Math,78.0
3,4,Dan,19,M,103,Gamma,Mr. Clark,Math,85.0
4,5,Eve,17,F,102,Beta,Ms. Brown,Math,88.0
5,6,Frank,18,M,101,Alpha,Mr. Adams,Math,72.0
6,7,Grace,16,F,103,Gamma,Mr. Clark,Math,95.0
7,8,Henry,15,M,102,Beta,Ms. Brown,Math,65.0
8,9,Ivy,17,F,101,Alpha,Mr. Adams,Math,91.0
9,10,Jack,18,M,103,Gamma,Mr. Clark,Math,55.0

In [78]:
# 5. Write a 4-5 sentence summary as if reporting to the school board

# in as much as gamma has the highest per class with 95, the other classes are not doing badly, beta with 90 and alpha with 91
# the female students are averaging 87.4 point score as against the male 73, while the gap is not alarming, targetted support for low performing male studentcolud help cover up th score.
# the lowest in the class is 55 by a male against 78 being the lowest by the female students, measures should be put in place to ensure improvement.
# from the average score per score of 81.5 by mr. adams, 78.3 by mr. clark and 81 by ms. brown, it is obvious the teacher might not be the problem.