In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None

In [132]:
df = pd.read_csv(r'C:\Users\user\Desktop\data-science-journey\Datasets\marketing_campaign.csv')
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Campaign_ID   2020 non-null   object
 1   Campaign_Name  2020 non-null   object
 2   Start_Date     2020 non-null   object
 3   End_Date       2020 non-null   object
 4   Channel        1919 non-null   object
 5   Impressions    2020 non-null   int64
 6   Clicks         2020 non-null   int64
 7   Spend          2020 non-null   object
 8   Conversions    1820 non-null   float64
 9   Active         2020 non-null   object
 10  Clicks         40 non-null     float64
 11  Campaign_Tag   2020 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 189.5+ KB

In [134]:
df.isnull().sum()

 Campaign_ID        0
Campaign_Name       0
Start_Date          0
End_Date            0
Channel           101
Impressions         0
Clicks              0
Spend               0
Conversions       200
Active              0
Clicks           1980
Campaign_Tag        0
dtype: int64

In [135]:
df.columns

Index([' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel',
       'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks',
       'Campaign_Tag'],
      dtype='object')

DATA CLEANING

In [136]:
# clean the column names of white soaces

df.rename(columns = {' Campaign_ID ': 'Campaign_ID', 'Clicks ': 'Clicks'}, inplace = True)
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [137]:
# check for duplicates

df.duplicated().sum()

np.int64(19)

In [138]:
# remove duplicates

df = df.drop_duplicates()
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06 00:00:00,2023-12-18,Facebook,84847,2616,4528.0,449.0,0,NaN,FA
1997,CMP-01998,Q4_BlackFriday_CMP-01998,2023-12-31 00:00:00,2024-01-14,Instagram,29380,705,767.32,NaN,False,NaN,IN
1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31 00:00:00,2023-11-24,Instagram,3356,124,145.24,18.0,0,NaN,IN
1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19 00:00:00,2023-03-04,TikTok,71326,2877,4588.82,245.0,True,NaN,TI
2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21 00:00:00,2023-12-29,E-mail,87143,2204,2649.14,391.0,Yes,NaN,E-

In [139]:
# drop the duplicated clicks column

df = df.loc[:, ~df.columns.duplicated()]
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA

In [140]:
# cleaning each columns and changing data types

# start date

df['Start_Date'] = pd.to_datetime(df['Start_Date'], format = 'mixed', errors = 'coerce')
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA

In [141]:
# end date

df['End_Date'] = pd.to_datetime(df['End_Date'], format = 'mixed', errors = 'coerce')
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA

In [142]:
df['End_Date'].dtypes

dtype('<M8[ns]')

In [143]:
# check and clean channel column

df['Channel'].unique()

array(['TikTok', 'Facebook', 'Email', 'Instagram', 'Google Ads', 'E-mail',
       nan, 'Gogle', 'Tik_Tok', 'Facebok', 'Insta_gram'], dtype=object)

In [144]:
# correct the spelling of some of the data

df['Channel'] = df['Channel'].replace({'Tik_Tok': 'TikTok', 'Facebok':  'Facebook', 'Insta_gram': 'Instagram', 'Gogle': 'Google Ads', 'E-mail': 'Email'})
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA

In [145]:
df['Channel'].isnull().sum()

np.int64(100)

In [146]:
# fill the missing value on the channel column with 'unknown'

df['Channel'] = df['Channel'].fillna('Unknown')
df['Channel'].value_counts()

Channel
TikTok        412
Facebook      401
Email         376
Instagram     358
Google Ads    354
Unknown       100
Name: count, dtype: int64

In [147]:
# check the impressions column


df['Impressions'].dtypes

dtype('int64')

In [148]:
# check the clicks column

df['Clicks'].isnull().sum()

np.int64(0)

In [149]:
df.isnull().sum()

Campaign_ID        0
Campaign_Name      0
Start_Date         0
End_Date           0
Channel            0
Impressions        0
Clicks             0
Spend              0
Conversions      200
Active             0
Campaign_Tag       0
dtype: int64

In [150]:
# look into the spend column

df['Spend'].dtypes

dtype('O')

In [151]:
# remove the $ sign and convert to numeric

df['Spend'] = df['Spend'].str.lstrip('$')
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA

In [152]:
df['Spend'] = pd.to_numeric(df['Spend'], errors = 'coerce')
df['Spend'].dtypes

dtype('float64')

In [153]:
# look into the conversion column

df['Conversions'].isnull().sum()

np.int64(200)

In [154]:
# drop the null values

df = df.dropna(subset = ['Conversions'])
df['Conversions'].isnull().sum()

np.int64(0)

In [155]:
df.isnull().sum()

Campaign_ID      0
Campaign_Name    0
Start_Date       0
End_Date         0
Channel          0
Impressions      0
Clicks           0
Spend            0
Conversions      0
Active           0
Campaign_Tag     0
dtype: int64

In [156]:
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,FA
...,...,...,...,...,...,...,...,...,...,...,...
1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO
1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA
1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN
1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,True,TI
2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,Yes,E-

In [157]:
# look into the campaign tags 

df['Campaign_Tag'].unique()

array(['TI', 'FA', 'EM', 'IN', 'GO', 'E-', 'INVALID', 'XX'], dtype=object)

In [158]:
# look into the Active column

df['Active'].unique()

array(['Y', '0', 'No', 'True', 'Yes', '1', 'False'], dtype=object)

In [159]:
# replace y, yes, true with 1 and no, false with 0
# for easy calculation later on during EDA

df['Active'] = df['Active'].replace({'Y': 1, 'No': 0, 'True': 1, 'Yes': 1, 'False': 0})
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA
...,...,...,...,...,...,...,...,...,...,...,...
1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO
1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA
1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN
1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,1,TI
2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,1,E-

In [160]:
df['Active'] = df['Active'].astype(int)
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA

Logical validati

In [161]:
# 

(df['Clicks'] > df['Conversions']).sum()

np.int64(1801)

In [162]:
# cannot have negative spend, so we remove it

(df['Spend'] < 0).sum()

np.int64(18)

In [163]:
df = df[df['Spend'] >= 0]
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA
...,...,...,...,...,...,...,...,...,...,...,...
1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO
1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA
1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN
1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,1,TI
2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,1,E-

In [164]:
# check the end and start date

(df['End_Date'] > df['Start_Date']).sum()

np.int64(1684)

In [165]:
# a campaign cannot end when it has not even started

(df['Start_Date'] > df['End_Date']).sum()

np.int64(99)

In [166]:
# 99 rolls where the end is highe than the start date

df[df['Start_Date'] > df['End_Date']]

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
23,CMP-00024,Q4_Winter_CMP-00024,2023-05-06,2023-05-01,Instagram,29693,995,1793.94,179.0,0,IN
54,CMP-00055,Q1_Launch_CMP-00055,2023-09-01,2023-08-27,Google Ads,18159,471,563.31,33.0,0,GO
86,CMP-00087,Q2_Winter_CMP-00087,2023-10-06,2023-07-08,Instagram,83798,1612,1787.74,279.0,1,IN
97,CMP-00098,Q4_Summer_CMP-00098,2023-07-02,2023-02-26,Unknown,49984,1871,950.50,273.0,0,XX
117,CMP-00118,Q2_Summer_CMP-00118,2023-07-03,2023-03-23,Google Ads,9392,189,338.61,23.0,1,GO
...,...,...,...,...,...,...,...,...,...,...,...
1906,CMP-01907,Q3_Launch_CMP-01907,2023-07-04,2023-04-13,Facebook,7154,148,130.92,15.0,1,FA
1921,CMP-01922,Q4_Summer_CMP-01922,2023-10-04,2023-04-14,Google Ads,53269,579,545.66,56.0,1,GO
1941,CMP-01942,Q1_Winter_CMP-01942,2023-07-12,2023-07-07,Google Ads,53326,2057,2926.28,379.0,1,GO
1952,CMP-01953,Q4_Winter_CMP-01953,2023-09-26,2023-09-21,Email,63768,1939,2297.90,111.0,0,EM
1960,CMP-01961,Q2_Summer_CMP-01961,2023-09-06,2023-06-17,Facebook,34320,728,500.11,96.0,1,INVALID

In [167]:
# swapped the end date with start date

mask = df['Start_Date'] >  df['End_Date']

df.loc[mask, ['Start_Date', 'End_Date']] = df.loc[mask, ['End_Date', 'Start_Date']].values

In [169]:
(df['Start_Date'] > df['End_Date']).sum()

np.int64(0)

In [170]:
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA
...,...,...,...,...,...,...,...,...,...,...,...
1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO
1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA
1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN
1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,1,TI
2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,1,E-

PERFORMANCE METRICS

In [171]:
# feature engineering

df['Duration'] = df['End_Date'] - df['Start_Date']
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days

In [175]:
# click through rate

df['click_through_rate'] = df['Clicks']/ df['Impressions']
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262

In [177]:
# calculate the conversion rate

df['conversion_rate'] = df['Conversions']/df['Clicks']
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515

In [179]:
# cost per click

df['cost_per_click'] = df['Spend']/df['Clicks']
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523,0.521929
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333,0.811000
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498,1.569858
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865,1.079931
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515,1.493728

In [182]:
df['cost_acquisition'] = df['Spend']/df['Conversions']
df.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click,cost_acquisition
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523,0.521929,5.141000
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333,0.811000,24.330000
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498,1.569858,25.948824
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865,1.079931,16.150963
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515,1.493728,8.414667

In [183]:
df.to_csv('cleaned_marketing_campaign.csv')