In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'C:\Users\user\Desktop\data-science-journey\jupyter notebooks files\cleaned_marketing_campaign.csv')
df.head()

,Unnamed: 0,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click,cost_acquisition
0,0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523,0.521929,5.141000
1,1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333,0.811000,24.330000
2,2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498,1.569858,25.948824
3,3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865,1.079931,16.150963
4,4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515,1.493728,8.414667

Campaign analysis

In [14]:
df = df[df['Conversions'] > 0]
df

,Unnamed: 0,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click,cost_acquisition
0,0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523,0.521929,5.141000
1,1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333,0.811000,24.330000
2,2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498,1.569858,25.948824
3,3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865,1.079931,16.150963
4,4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515,1.493728,8.414667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1778,1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO,17 days,0.031914,0.080844,1.381441,17.087826
1779,1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA,12 days,0.030832,0.171636,1.730887,10.084633
1780,1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN,24 days,0.036949,0.145161,1.171290,8.068889
1781,1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,1,TI,13 days,0.040336,0.085158,1.595002,18.729878
1782,2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,1,E-,8 days,0.025292,0.177405,1.201969,6.775294

In [15]:
# the channel that performed best

df.groupby('Channel').agg({
    'conversion_rate': 'mean',
    'Spend': 'sum',
    'Conversions': 'sum',
    'click_through_rate': 'mean',
    'cost_acquisition': 'mean'
}).sort_values('conversion_rate', ascending = False)

# from this, it is clear that instagram performed best because 540k was spent on instagram and the conversion rate is 0.126 which has a ~0.001 difference from the 
# highest which spent almost 3x what was spent on instagram.

,conversion_rate,Spend,Conversions,click_through_rate,cost_acquisition
Channel,,,,,
Unknown,0.128622,162668.40,17742.0,0.031864,10.746601
Instagram,0.126475,540224.21,57009.0,0.029741,11.189245
Facebook,0.123742,1684259.72,68587.0,0.030192,26.522214
Email,0.122638,1647765.49,62884.0,0.029455,26.297094
Google Ads,0.121726,618660.20,60014.0,0.029871,12.209155
TikTok,0.120847,688530.48,67435.0,0.030092,11.883630

In [5]:
# campaign tag that perform best

df.groupby('Campaign_Tag').agg({
    'Spend': 'sum',
    'Conversions': 'sum',
    'cost_acquisition': 'mean'
}). sort_values('Conversions', ascending = False)

# from this, it is clear that TI campaign tag performed best, consumed less money ~651k and conversion of ~64k that is almost 3x lower than FA which consumed 1.65M
# with a conversion of ~66k

                   Spend  Conversions  cost_acquisition
Campaign_Tag
FA            1657278.68      65923.0         27.116364
TI             651320.23      64357.0         11.845583
EM            1084750.57      56833.0         18.039996
GO             576982.10      55710.0         12.342610
IN             527220.41      55149.0         11.353999
INVALID        671597.18      17335.0         45.249742
XX             142631.50      15972.0               inf
E-              30345.18       2392.0         14.527922

In [6]:
# more spend equals more conversions?

df[['Conversions', 'Spend']].corr()

# more spend does not equal conversion. from the analysis, to get a conversion of 1 you spend 0.057 
# and conversion of 0.057 you spend 1.

             Conversions     Spend
Conversions     1.000000  0.057365
Spend           0.057365  1.000000

In [7]:
# worst campaign

df.sort_values('cost_acquisition', ascending = False).head(5)

# worst campaign tag is xx, followed by FA and channel is unknown followed by facebook

,Unnamed: 0,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click,cost_acquisition
1314,1470,CMP-01471,Q2_Summer_CMP-01471,2023-11-12,2023-11-13,Unknown,1060,11,17.35,0.0,0,XX,1 days,0.010377,0.000000,1.577273,inf
1306,1460,CMP-01461,Q4_Launch_CMP-01461,2023-09-20,2023-09-27,Facebook,39890,1193,500000.00,160.0,1,FA,7 days,0.029907,0.134116,419.111484,3125.000000
1569,1754,CMP-01755,Q1_Summer_CMP-01755,2023-06-30,2023-07-10,Email,34062,1392,500000.00,165.0,0,INVALID,10 days,0.040867,0.118534,359.195402,3030.303030
703,789,CMP-00790,Q2_Summer_CMP-00790,2023-12-10,2024-01-06,Facebook,87704,4272,500000.00,237.0,0,FA,27 days,0.048709,0.055478,117.041199,2109.704641
1536,1718,CMP-01719,Q1_Winter_CMP-01719,2023-05-31,2023-06-02,Email,87231,1585,500000.00,265.0,0,EM,2 days,0.018170,0.167192,315.457413,1886.792453

,Unnamed: 0,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Campaign_Tag,Duration,click_through_rate,conversion_rate,cost_per_click,cost_acquisition
0,0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,1,TI,19 days,0.011730,0.101523,0.521929,5.141000
1,1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,0,FA,6 days,0.016129,0.033333,0.811000,24.330000
2,2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,0,EM,7 days,0.010833,0.060498,1.569858,25.948824
3,3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,1,TI,4 days,0.036127,0.066865,1.079931,16.150963
4,4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,1,FA,1 days,0.023262,0.177515,1.493728,8.414667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1778,1995,CMP-01996,Q2_BlackFriday_CMP-01996,2023-06-25,2023-07-12,Google Ads,71316,2276,3144.16,184.0,1,GO,17 days,0.031914,0.080844,1.381441,17.087826
1779,1996,CMP-01997,Q4_Winter_CMP-01997,2023-12-06,2023-12-18,Facebook,84847,2616,4528.00,449.0,0,FA,12 days,0.030832,0.171636,1.730887,10.084633
1780,1998,CMP-01999,Q1_Launch_CMP-01999,2023-10-31,2023-11-24,Instagram,3356,124,145.24,18.0,0,IN,24 days,0.036949,0.145161,1.171290,8.068889
1781,1999,CMP-02000,Q2_Winter_CMP-02000,2023-02-19,2023-03-04,TikTok,71326,2877,4588.82,245.0,1,TI,13 days,0.040336,0.085158,1.595002,18.729878
1782,2008,CMP-01377,Q1_Winter_CMP-01377,2023-12-21,2023-12-29,Email,87143,2204,2649.14,391.0,1,E-,8 days,0.025292,0.177405,1.201969,6.775294

In [16]:
df.groupby('Channel').apply(
    lambda x : x['Spend'].sum()/ x['Conversions'].sum()
)

C:\Users\user\AppData\Local\Temp\ipykernel_11888\1978101335.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Channel').apply(

Channel
Email         26.203255
Facebook      24.556545
Google Ads    10.308598
Instagram      9.476121
TikTok        10.210284
Unknown        9.168549
dtype: float64