In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)

student_score = np.random.randint(30, 100, size = (30, 5))
subjects = ['math', 'english', 'science', 'history', 'cs']

df = pd.DataFrame(student_score, columns = subjects)

df.index = [f"student_{i}" for i in range(30)]

df

            math  english  science  history  cs
student_0     74       77       94       97  97
student_1     39       51       66       42  88
student_2     95       69       76       67  55
student_3     39       50       99       77  94
student_4     79       59       49       49  44
student_5     69       62       95       39  87
student_6     62       61       53       65  85
student_7     58       64       30       30  66
student_8     83       35       68       47  34
student_9     72       88       61       31  95
student_10    71       87       65       41  76
student_11    30       44       83       42  72
student_12    98       36       98       77  33
student_13    82       45       50       88  53
student_14    43       78       79       99  71
student_15    65       94       99       30  80
student_16    66       64       78       33  72
student_17    51       30       40       73  88
student_18    53       89       32       92  65
student_19    97       76       50       80  57
student_20    44       71       88       95  66
student_21    40       73       41       32  81
student_22    62       84       30       68  49
student_23    76       72       86       90  60
student_24    54       32       33       43  70
student_25    49       56       96       82  97
student_26    91       44       34       97  41
student_27    86       46       54       59  51
student_28    55       90       91       63  62
student_29    61       43       86       54  71

In [3]:
df.head()

           math  english  science  history  cs
student_0    74       77       94       97  97
student_1    39       51       66       42  88
student_2    95       69       76       67  55
student_3    39       50       99       77  94
student_4    79       59       49       49  44

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, student_0 to student_29
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   math     30 non-null     int32
 1   english  30 non-null     int32
 2   science  30 non-null     int32
 3   history  30 non-null     int32
 4   cs       30 non-null     int32
dtypes: int32(5)
memory usage: 840.0+ bytes

In [5]:
df.shape

(30, 5)

In [6]:
df.tail()

            math  english  science  history  cs
student_25    49       56       96       82  97
student_26    91       44       34       97  41
student_27    86       46       54       59  51
student_28    55       90       91       63  62
student_29    61       43       86       54  71

In [7]:
df.dtypes

math       int32
english    int32
science    int32
history    int32
cs         int32
dtype: object

In [8]:
df.describe()

            math    english    science    history         cs
count  30.000000  30.000000  30.000000  30.000000  30.000000
mean   64.800000  62.333333  66.800000  62.733333  68.666667
std    18.817453  19.072156  23.943036  23.463741  18.497592
min    30.000000  30.000000  30.000000  30.000000  33.000000
25%    51.500000  45.250000  49.250000  42.000000  55.500000
50%    63.500000  63.000000  67.000000  64.000000  70.500000
75%    78.250000  76.750000  87.500000  81.500000  84.000000
max    98.000000  94.000000  99.000000  99.000000  97.000000

In [9]:
df['math']

student_0     74
student_1     39
student_2     95
student_3     39
student_4     79
student_5     69
student_6     62
student_7     58
student_8     83
student_9     72
student_10    71
student_11    30
student_12    98
student_13    82
student_14    43
student_15    65
student_16    66
student_17    51
student_18    53
student_19    97
student_20    44
student_21    40
student_22    62
student_23    76
student_24    54
student_25    49
student_26    91
student_27    86
student_28    55
student_29    61
Name: math, dtype: int32

In [10]:
df[['math', 'english', 'cs','history']]

            math  english  cs  history
student_0     74       77  97       97
student_1     39       51  88       42
student_2     95       69  55       67
student_3     39       50  94       77
student_4     79       59  44       49
student_5     69       62  87       39
student_6     62       61  85       65
student_7     58       64  66       30
student_8     83       35  34       47
student_9     72       88  95       31
student_10    71       87  76       41
student_11    30       44  72       42
student_12    98       36  33       77
student_13    82       45  53       88
student_14    43       78  71       99
student_15    65       94  80       30
student_16    66       64  72       33
student_17    51       30  88       73
student_18    53       89  65       92
student_19    97       76  57       80
student_20    44       71  66       95
student_21    40       73  81       32
student_22    62       84  49       68
student_23    76       72  60       90
student_24    54       32  70       43
student_25    49       56  97       82
student_26    91       44  41       97
student_27    86       46  51       59
student_28    55       90  62       63
student_29    61       43  71       54

LABEL BASED SELECTION FOR PANDAS (.LOC)

note: the first and last value is inclusive

In [11]:
df.loc['student_28']

math       55
english    90
science    91
history    63
cs         62
Name: student_28, dtype: int32

In [12]:
df.loc['student_0', 'math']

np.int32(74)

In [13]:
df.loc['student_1': 'student_4', 'math' : 'cs']

           math  english  science  history  cs
student_1    39       51       66       42  88
student_2    95       69       76       67  55
student_3    39       50       99       77  94
student_4    79       59       49       49  44

In [14]:
df.loc['student_2', 'math': 'cs']

math       95
english    69
science    76
history    67
cs         55
Name: student_2, dtype: int32

In [15]:
df.loc['student_0': 'student_10', 'math': 'cs']

            math  english  science  history  cs
student_0     74       77       94       97  97
student_1     39       51       66       42  88
student_2     95       69       76       67  55
student_3     39       50       99       77  94
student_4     79       59       49       49  44
student_5     69       62       95       39  87
student_6     62       61       53       65  85
student_7     58       64       30       30  66
student_8     83       35       68       47  34
student_9     72       88       61       31  95
student_10    71       87       65       41  76

INDEX BASED SELECTION ON PANDAS (.ILOC)

note: the first value is inclusive but the last is not

In [16]:
df.iloc[0]

math       74
english    77
science    94
history    97
cs         97
Name: student_0, dtype: int32

In [17]:
df.iloc[0:3]

           math  english  science  history  cs
student_0    74       77       94       97  97
student_1    39       51       66       42  88
student_2    95       69       76       67  55

In [18]:
df.iloc[0, 2]

np.int32(94)

In [19]:
df.iloc[: 5, : 3]

           math  english  science
student_0    74       77       94
student_1    39       51       66
student_2    95       69       76
student_3    39       50       99
student_4    79       59       49

In [20]:
#SERIES


math_score = df['math']

type(math_score)

pandas.core.series.Series

In [21]:
math_score.mean()

np.float64(64.8)

In [22]:
math_score.value_counts()

math
39    2
62    2
95    1
74    1
79    1
69    1
58    1
83    1
72    1
71    1
30    1
98    1
82    1
43    1
65    1
66    1
51    1
53    1
97    1
44    1
40    1
76    1
54    1
49    1
91    1
86    1
55    1
61    1
Name: count, dtype: int64

In [23]:
math_score.sort_values(ascending = False)

student_12    98
student_19    97
student_2     95
student_26    91
student_27    86
student_8     83
student_13    82
student_4     79
student_23    76
student_0     74
student_9     72
student_10    71
student_5     69
student_16    66
student_15    65
student_6     62
student_22    62
student_29    61
student_7     58
student_28    55
student_24    54
student_18    53
student_17    51
student_25    49
student_20    44
student_14    43
student_21    40
student_1     39
student_3     39
student_11    30
Name: math, dtype: int32

In [24]:
math_score.describe()

count    30.000000
mean     64.800000
std      18.817453
min      30.000000
25%      51.500000
50%      63.500000
75%      78.250000
max      98.000000
Name: math, dtype: float64

In [7]:
def first_looks(df):
    print(f" shape: {df.shape}")
    print(f"\n --- first 5 rows ---")
    print(df.head())
    print(f"\n --- the data types ---")
    print(df.dtypes)
    print(f"\n --- misssing values ---")
    print(df.isnull().sum())
    print(f"\n --- statistical summary ---")
    print(df.describe())

first_looks(df)

 shape: (50, 8)

 --- first 5 rows ---
   student_id       name  age gender  math  english  science classes
0           1  student_1   17      F    70       58       86       C
1           2  student_2   15      M    66       50       53       B
2           3  student_3   17      M    78       98       54       A
3           4  student_4   18      M    55       52       34       A
4           5  student_5   18      M    97       37       79       B

 --- the data types ---
student_id     int64
name          object
age            int32
gender        object
math           int32
english        int32
science        int32
classes       object
dtype: object

 --- misssing values ---
student_id    0
name          0
age           0
gender        0
math          0
english       0
science       0
classes       0
dtype: int64

 --- statistical summary ---
       student_id        age       math    english    science
count    50.00000  50.000000  50.000000  50.000000  50.000000
mean     25.50000  16.740000  65.920000  64.000000  62.060000
std      14.57738   1.139459  18.431163  20.406082  20.530127
min       1.00000  15.000000  30.000000  30.000000  30.000000
25%      13.25000  16.000000  51.250000  43.750000  48.500000
50%      25.50000  17.000000  65.500000  66.500000  60.500000
75%      37.75000  18.000000  78.750000  81.750000  80.500000
max      50.00000  18.000000  99.000000  98.000000  99.000000

QUERYING NAD FILTERING

In [109]:
df.query('math > 80')

,math,english,science,history,computer science,average,total,grade,status,statue
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_8,83,35,68,47,34,53.4,267,D,at risk,at risk
student_12,98,36,98,77,33,68.4,342,C,satisfactory,satisfactory
student_13,82,45,50,88,53,63.6,318,C,satisfactory,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory,satisfactory
student_26,91,44,34,97,41,61.4,307,C,satisfactory,satisfactory
student_27,86,46,54,59,51,59.2,296,D,at risk,at risk

In [30]:
df[df['math'] > 80]

            math  english  science  history  cs
student_2     95       69       76       67  55
student_8     83       35       68       47  34
student_12    98       36       98       77  33
student_13    82       45       50       88  53
student_19    97       76       50       80  57
student_26    91       44       34       97  41
student_27    86       46       54       59  51

In [39]:
df[(df['math'] > 80) & (df['cs'] > 50)]

            math  english  science  history  cs
student_2     95       69       76       67  55
student_13    82       45       50       88  53
student_19    97       76       50       80  57
student_27    86       46       54       59  51

In [40]:
df[(df['math'] < 50) | (df['cs'] < 50)]

            math  english  science  history  cs
student_1     39       51       66       42  88
student_3     39       50       99       77  94
student_4     79       59       49       49  44
student_8     83       35       68       47  34
student_11    30       44       83       42  72
student_12    98       36       98       77  33
student_14    43       78       79       99  71
student_20    44       71       88       95  66
student_21    40       73       41       32  81
student_22    62       84       30       68  49
student_25    49       56       96       82  97
student_26    91       44       34       97  41

In [42]:
df.query('math > 80')

            math  english  science  history  cs
student_2     95       69       76       67  55
student_8     83       35       68       47  34
student_12    98       36       98       77  33
student_13    82       45       50       88  53
student_19    97       76       50       80  57
student_26    91       44       34       97  41
student_27    86       46       54       59  51

In [46]:
df.query('math > 80 and cs > 50')

            math  english  science  history  cs
student_2     95       69       76       67  55
student_13    82       45       50       88  53
student_19    97       76       50       80  57
student_27    86       46       54       59  51

In [50]:
df.query('math > 800 or history > 70')

            math  english  science  history  cs
student_0     74       77       94       97  97
student_3     39       50       99       77  94
student_12    98       36       98       77  33
student_13    82       45       50       88  53
student_14    43       78       79       99  71
student_17    51       30       40       73  88
student_18    53       89       32       92  65
student_19    97       76       50       80  57
student_20    44       71       88       95  66
student_23    76       72       86       90  60
student_25    49       56       96       82  97
student_26    91       44       34       97  41

In [53]:
df[df['math'].isin([85 ,90, 95])]

           math  english  science  history  cs
student_2    95       69       76       67  55

In [55]:
high_score = df.query('math > 80').sort_values('math', ascending = False)

high_score

            math  english  science  history  cs
student_12    98       36       98       77  33
student_19    97       76       50       80  57
student_2     95       69       76       67  55
student_26    91       44       34       97  41
student_27    86       46       54       59  51
student_8     83       35       68       47  34
student_13    82       45       50       88  53

In [58]:
highest_eng_score = df.query('english > 70').sort_values('english', ascending = False)

highest_eng_score

            math  english  science  history  cs
student_15    65       94       99       30  80
student_28    55       90       91       63  62
student_18    53       89       32       92  65
student_9     72       88       61       31  95
student_10    71       87       65       41  76
student_22    62       84       30       68  49
student_14    43       78       79       99  71
student_0     74       77       94       97  97
student_19    97       76       50       80  57
student_21    40       73       41       32  81
student_23    76       72       86       90  60
student_20    44       71       88       95  66

In [60]:
top_science_score = df.query('science > 80').sort_values('science', ascending = False)

top_science_score

            math  english  science  history  cs
student_3     39       50       99       77  94
student_15    65       94       99       30  80
student_12    98       36       98       77  33
student_25    49       56       96       82  97
student_5     69       62       95       39  87
student_0     74       77       94       97  97
student_28    55       90       91       63  62
student_20    44       71       88       95  66
student_23    76       72       86       90  60
student_29    61       43       86       54  71
student_11    30       44       83       42  72

ADDING AND TRANSFORMING COLUMNS

In [62]:
# ADDING A COLUMN

df['average'] = df.mean(axis = 1).round(2)

df.head()

           math  english  science  history  cs  average
student_0    74       77       94       97  97     87.8
student_1    39       51       66       42  88     57.2
student_2    95       69       76       67  55     72.4
student_3    39       50       99       77  94     71.8
student_4    79       59       49       49  44     56.0

In [63]:
df['total'] = df.sum(axis = 1)

df.head()

           math  english  science  history  cs  average  total
student_0    74       77       94       97  97     87.8  526.8
student_1    39       51       66       42  88     57.2  343.2
student_2    95       69       76       67  55     72.4  434.4
student_3    39       50       99       77  94     71.8  430.8
student_4    79       59       49       49  44     56.0  336.0

In [66]:
df.head()

           math  english  science  history  cs  average
student_0    74       77       94       97  97     87.8
student_1    39       51       66       42  88     57.2
student_2    95       69       76       67  55     72.4
student_3    39       50       99       77  94     71.8
student_4    79       59       49       49  44     56.0

In [73]:
df['total'] = df[['math', 'english', 'science', 'history', 'cs']].sum(axis = 1)

df.head()

           math  english  science  history  cs  average  total
student_0    74       77       94       97  97     87.8    439
student_1    39       51       66       42  88     57.2    286
student_2    95       69       76       67  55     72.4    362
student_3    39       50       99       77  94     71.8    359
student_4    79       59       49       49  44     56.0    280

In [76]:
df['grade'] = pd.cut(
    df['average'],
    bins = [0,50, 60, 70, 80, 100],
    labels = ['F', 'D', 'C', 'B', 'A']
)

df

            math  english  science  history  cs  average  total grade
student_0     74       77       94       97  97     87.8    439     A
student_1     39       51       66       42  88     57.2    286     D
student_2     95       69       76       67  55     72.4    362     B
student_3     39       50       99       77  94     71.8    359     B
student_4     79       59       49       49  44     56.0    280     D
student_5     69       62       95       39  87     70.4    352     B
student_6     62       61       53       65  85     65.2    326     C
student_7     58       64       30       30  66     49.6    248     F
student_8     83       35       68       47  34     53.4    267     D
student_9     72       88       61       31  95     69.4    347     C
student_10    71       87       65       41  76     68.0    340     C
student_11    30       44       83       42  72     54.2    271     D
student_12    98       36       98       77  33     68.4    342     C
student_13    82       45       50       88  53     63.6    318     C
student_14    43       78       79       99  71     74.0    370     B
student_15    65       94       99       30  80     73.6    368     B
student_16    66       64       78       33  72     62.6    313     C
student_17    51       30       40       73  88     56.4    282     D
student_18    53       89       32       92  65     66.2    331     C
student_19    97       76       50       80  57     72.0    360     B
student_20    44       71       88       95  66     72.8    364     B
student_21    40       73       41       32  81     53.4    267     D
student_22    62       84       30       68  49     58.6    293     D
student_23    76       72       86       90  60     76.8    384     B
student_24    54       32       33       43  70     46.4    232     F
student_25    49       56       96       82  97     76.0    380     B
student_26    91       44       34       97  41     61.4    307     C
student_27    86       46       54       59  51     59.2    296     D
student_28    55       90       91       63  62     72.2    361     B
student_29    61       43       86       54  71     63.0    315     C

In [80]:
df['grade'].value_counts(ascending = True)

grade
A     1
F     2
D     8
C     9
B    10
Name: count, dtype: int64

In [84]:
# np.select for conditional columns — faster than apply

conditions = [
    df['average'] > 80,
    df['average'] >= 60,
    df['average'] < 60
]

choices = ['High performaer', 'satisfactory', 'at risk']

df['statue'] = np.select(conditions, choices, default = 'Unknown')

df

,math,english,science,history,cs,average,total,grade,statue
student_0,74,77,94,97,97,87.8,439,A,High performaer
student_1,39,51,66,42,88,57.2,286,D,at risk
student_2,95,69,76,67,55,72.4,362,B,satisfactory
student_3,39,50,99,77,94,71.8,359,B,satisfactory
student_4,79,59,49,49,44,56.0,280,D,at risk
student_5,69,62,95,39,87,70.4,352,B,satisfactory
student_6,62,61,53,65,85,65.2,326,C,satisfactory
student_7,58,64,30,30,66,49.6,248,F,at risk
student_8,83,35,68,47,34,53.4,267,D,at risk
student_9,72,88,61,31,95,69.4,347,C,satisfactory
student_10,71,87,65,41,76,68.0,340,C,satisfactory
student_11,30,44,83,42,72,54.2,271,D,at risk
student_12,98,36,98,77,33,68.4,342,C,satisfactory
student_13,82,45,50,88,53,63.6,318,C,satisfactory
student_14,43,78,79,99,71,74.0,370,B,satisfactory
student_15,65,94,99,30,80,73.6,368,B,satisfactory
student_16,66,64,78,33,72,62.6,313,C,satisfactory
student_17,51,30,40,73,88,56.4,282,D,at risk
student_18,53,89,32,92,65,66.2,331,C,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory
student_20,44,71,88,95,66,72.8,364,B,satisfactory
student_21,40,73,41,32,81,53.4,267,D,at risk
student_22,62,84,30,68,49,58.6,293,D,at risk
student_23,76,72,86,90,60,76.8,384,B,satisfactory
student_24,54,32,33,43,70,46.4,232,F,at risk
student_25,49,56,96,82,97,76.0,380,B,satisfactory
student_26,91,44,34,97,41,61.4,307,C,satisfactory
student_27,86,46,54,59,51,59.2,296,D,at risk
student_28,55,90,91,63,62,72.2,361,B,satisfactory
student_29,61,43,86,54,71,63.0,315,C,satisfactory

In [87]:
df['statue'].value_counts()

statue
satisfactory       19
at risk            10
High performaer     1
Name: count, dtype: int64

In [90]:
df.rename(columns = {'statue': 'status', 'cs': 'computer science'}, inplace = True)

df.head()

,math,english,science,history,computer science,average,total,grade,status
student_0,74,77,94,97,97,87.8,439,A,High performaer
student_1,39,51,66,42,88,57.2,286,D,at risk
student_2,95,69,76,67,55,72.4,362,B,satisfactory
student_3,39,50,99,77,94,71.8,359,B,satisfactory
student_4,79,59,49,49,44,56.0,280,D,at risk

GROUPBY AND AGGREGATION

In [94]:
# GroupBy is where Pandas truly shines
# Think of it as: split data into groups → apply function → combine results

df['statue'] = np.select(
    [df['average'] > 80, df['average'] >= 60],
    ['High performer', 'satisfactory'],
    default = 'at risk'
)

df.head()

,math,english,science,history,computer science,average,total,grade,status,statue
student_0,74,77,94,97,97,87.8,439,A,High performaer,High performer
student_1,39,51,66,42,88,57.2,286,D,at risk,at risk
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_3,39,50,99,77,94,71.8,359,B,satisfactory,satisfactory
student_4,79,59,49,49,44,56.0,280,D,at risk,at risk

In [97]:
df.groupby('status')['average'].mean().round(2)

status
High performaer    87.80
at risk            54.44
satisfactory       69.46
Name: average, dtype: float64

In [102]:
# Multiple aggregations at once

df.groupby('status').agg(
    count = ('average', 'count'),
    mean_average = ('average', 'mean'),
    math_best = ('math', 'max'),
    history_worst = ('history', 'min')
).round(2).sort_values(by = 'mean_average', ascending = False)

                 count  mean_average  math_best  history_worst
status
High performaer      1         87.80         74             97
satisfactory        19         69.46         98             30
at risk             10         54.44         86             30

In [107]:
df.groupby(['status', 'grade'])['average'].mean()

C:\Users\user\AppData\Local\Temp\ipykernel_4188\1167178723.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['status', 'grade'])['average'].mean()

status           grade
High performaer  F              NaN
                 D              NaN
                 C              NaN
                 B              NaN
                 A        87.800000
at risk          F        48.000000
                 D        56.050000
                 C              NaN
                 B              NaN
                 A              NaN
satisfactory     F              NaN
                 D              NaN
                 C        65.311111
                 B        73.200000
                 A              NaN
Name: average, dtype: float64

In [110]:
df[(df['math'] > 80) & (df['english'] > 60) & (df['history'] > 50)]

,math,english,science,history,computer science,average,total,grade,status,statue
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory,satisfactory

In [112]:
df.query('math > 80 and english > 60 and history > 50')

,math,english,science,history,computer science,average,total,grade,status,statue
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory,satisfactory

In [115]:
df[(df['math'] > 80) & (df['english'] > 60) & (df['grade'] == 'B')]

,math,english,science,history,computer science,average,total,grade,status,statue
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory,satisfactory

In [120]:
df.query('math > 80 and english > 60 and grade == "B"')

,math,english,science,history,computer science,average,total,grade,status,statue
student_2,95,69,76,67,55,72.4,362,B,satisfactory,satisfactory
student_19,97,76,50,80,57,72.0,360,B,satisfactory,satisfactory

In [121]:
type(df['math'])

pandas.core.series.Series

In [123]:
type(df[['math']])

pandas.core.frame.DataFrame

In [124]:
df['math'].value_counts()

math
39    2
62    2
95    1
74    1
79    1
69    1
58    1
83    1
72    1
71    1
30    1
98    1
82    1
43    1
65    1
66    1
51    1
53    1
97    1
44    1
40    1
76    1
54    1
49    1
91    1
86    1
55    1
61    1
Name: count, dtype: int64

In [125]:
df[['math']].value_counts()

math
39      2
62      2
40      1
30      1
44      1
49      1
51      1
53      1
54      1
55      1
58      1
43      1
61      1
65      1
66      1
69      1
71      1
72      1
74      1
76      1
79      1
82      1
83      1
86      1
91      1
95      1
97      1
98      1
Name: count, dtype: int64

In [13]:
#np.random.seed(42)

data = {
    'student_id': range(1, 51),
    'name': [f'student_{i}' for i in range(1, 51)],
    'age': np.random.randint(15, 19, 50),
    'gender': np.random.choice(['F', 'M'], 50),
    'math': np.random.randint(30, 100, 50),
    'english': np.random.randint(30, 100, 50),
    'science': np.random.randint(30, 100, 50),
    'classes': np.random.choice(['A', 'B', 'C'], 50)
}

df = pd.DataFrame(data)
df.head()

   student_id       name  age gender  math  english  science classes
0           1  student_1   15      M    90       48       69       C
1           2  student_2   16      M    67       37       58       B
2           3  student_3   16      F    73       83       54       B
3           4  student_4   18      M    50       76       48       B
4           5  student_5   16      M    36       63       97       B

In [14]:
# Exercise 1
# Select only students from Class A who scored above 70 in Math.

class_a_high_math = df[(df['math'] > 70) & (df['classes'] == 'A')]

class_a_high_math[['name', 'math']]

          name  math
7    student_8    96
8    student_9    99
25  student_26    75
27  student_28    77
28  student_29    89
30  student_31    97
32  student_33    87
34  student_35    99
35  student_36    88
38  student_39    99
42  student_43    99

In [5]:
# Show only their name, math, and english columns.

class_a_high_math[['name', 'math', 'english']].head()

          name  math  english
2    student_3    78       98
23  student_24    79       83
24  student_25    71       88
30  student_31    93       83
34  student_35    93       65

In [9]:
# Exercise 2
# Add a column called 'average' (mean of math, english, science)

df['average'] = df[['math', 'english', 'science']].mean(axis = 1).round(2)

df.head()

   student_id       name  age gender  math  english  science classes  average
0           1  student_1   17      F    70       58       86       C    71.33
1           2  student_2   15      M    66       50       53       B    56.33
2           3  student_3   17      M    78       98       54       A    76.67
3           4  student_4   18      M    55       52       34       A    47.00
4           5  student_5   18      M    97       37       79       B    71.00

In [10]:
# Add a column called 'status':
#   - 'Distinction' if average >= 80
#   - 'Pass' if average >= 50
#   - 'Fail' if average < 50


df['status'] = np.select(
    [df['average'] >= 80, df['average'] >= 50, df['average'] < 50],
    ['Distinction', 'pass', 'fail'], default = 'Unknown')
df.head()

,student_id,name,age,gender,math,english,science,classes,average,status
0,1,student_1,17,F,70,58,86,C,71.33,pass
1,2,student_2,15,M,66,50,53,B,56.33,pass
2,3,student_3,17,M,78,98,54,A,76.67,pass
3,4,student_4,18,M,55,52,34,A,47.00,fail
4,5,student_5,18,M,97,37,79,B,71.00,pass

In [11]:
"""""

conditions = [
    df['average'] >= 80,
    df['average'] >= 50,
    df['average'] < 50
]

stats = ['Distinction', 'Pass', 'fail']

df['satue'] = np.select(conditions, stats, default = 'Unknown')

df.head()

"""

'""\n\nconditions = [\n    df[\'average\'] >= 80,\n    df[\'average\'] >= 50,\n    df[\'average\'] < 50\n]\n\nstats = [\'Distinction\', \'Pass\', \'fail\']\n\ndf[\'satue\'] = np.select(conditions, stats, default = \'Unknown\')\n\ndf.head()\n\n'

In [12]:
df.head()

,student_id,name,age,gender,math,english,science,classes,average,status
0,1,student_1,17,F,70,58,86,C,71.33,pass
1,2,student_2,15,M,66,50,53,B,56.33,pass
2,3,student_3,17,M,78,98,54,A,76.67,pass
3,4,student_4,18,M,55,52,34,A,47.00,fail
4,5,student_5,18,M,97,37,79,B,71.00,pass

In [16]:
# Exercise 3
# Using groupby, find for each class (A, B, C):
#   - Number of students


df.groupby('classes')['name'].count()

classes
A    18
B    18
C    14
Name: name, dtype: int64

In [21]:
#   - Average score across math, english, science

df.groupby('classes').agg(
    number_student = ('name', 'count'),
    math_avg = ('math', 'mean'),
    english_avg = ('english', 'mean'),
    science_avg = ('science', 'mean'),
    total_avg = ('average', 'mean')    
).round(2)

         number_student  math_avg  english_avg  science_avg  total_avg
classes
A                    18     66.56        64.56        57.11      62.74
B                    18     66.56        61.28        67.56      65.13
C                    14     64.29        66.79        61.36      64.14

In [23]:
#   - Number of students who failed (average < 50)

df[df['average'] < 50].groupby('classes')['name'].count()

classes
A    3
B    2
C    1
Name: name, dtype: int64

In [27]:
# Exercise 4
# Find the top student (highest average) in each class.
# Output should show class, student name, and their average.

idx = df.groupby('classes')['average'].idxmax()

df.loc[idx, ['classes', 'name', 'average' ]].sort_values(by = 'average', ascending = False)

   classes        name  average
35       C  student_36    91.67
48       B  student_49    87.00
24       A  student_25    84.67

In [38]:
# Exercise 5
# Find which gender has a higher average score overall.

df.groupby('gender')['average'].mean().round(2)

gender
F    65.67
M    62.88
Name: average, dtype: float64

In [36]:
# Then break it down: which gender performs better in each subject?

df.groupby('gender')[['math', 'english', 'science']].mean().round(2)

        math  english  science
gender
F       66.7    65.25    65.05
M       65.4    63.17    60.07

In [40]:
df[df['status'] == 'Distinction'].groupby('gender')['name'].count()

gender
F    3
M    2
Name: name, dtype: int64

In [41]:
# Run these and paste the results
df.groupby('gender')[['math', 'english', 'science']].mean().round(2)

df[df['status'] == 'Distinction'].groupby('gender')['name'].count()

gender
F    3
M    2
Name: name, dtype: int64

In [11]:
# 1. DATA OVERVIEW
#    Run a proper first_look() function on the dataset

def first_look(df):
    print('data shape', df.shape)
    print('\n --- First 5 rolls---' )
    print(df.head())
    print('\n --- the data types ---')
    print(df.dtypes)
    print('\n --- missing values ---')
    print(df.isnull().sum())
    print('\n --- statistics of data ---')
    print(df.describe())

first_look(df)

data shape (50, 8)

 --- First 5 rolls---
   student_id       name  age gender  math  english  science classes
0           1  student_1   17      F    70       58       86       C
1           2  student_2   15      M    66       50       53       B
2           3  student_3   17      M    78       98       54       A
3           4  student_4   18      M    55       52       34       A
4           5  student_5   18      M    97       37       79       B

 --- the data types ---
student_id     int64
name          object
age            int32
gender        object
math           int32
english        int32
science        int32
classes       object
dtype: object

 --- missing values ---
student_id    0
name          0
age           0
gender        0
math          0
english       0
science       0
classes       0
dtype: int64

 --- statistics of data ---
       student_id        age       math    english    science
count    50.00000  50.000000  50.000000  50.000000  50.000000
mean     25.50000  16.740000  65.920000  64.000000  62.060000
std      14.57738   1.139459  18.431163  20.406082  20.530127
min       1.00000  15.000000  30.000000  30.000000  30.000000
25%      13.25000  16.000000  51.250000  43.750000  48.500000
50%      25.50000  17.000000  65.500000  66.500000  60.500000
75%      37.75000  18.000000  78.750000  81.750000  80.500000
max      50.00000  18.000000  99.000000  98.000000  99.000000

In [32]:

# 2. ENRICHMENT
#    Add these columns:
#    - 'average' (mean of 3 subjects)

df['average'] = df[['math', 'english', 'science']].mean(axis = 1).round(2)

In [33]:
df.head()

   student_id       name  age gender  math  english  science classes  average
0           1  student_1   15      M    90       48       69       C    69.00
1           2  student_2   16      M    67       37       58       B    54.00
2           3  student_3   16      F    73       83       54       B    70.00
3           4  student_4   18      M    50       76       48       B    58.00
4           5  student_5   16      M    36       63       97       B    65.33

In [38]:
#    - 'grade' (A/B/C/D/F using pd.cut)

df['grade'] = pd.cut(
    df['average'],
    bins = [0, 50, 60, 70, 80, 100],
    labels = ['F', 'D', 'C', 'B', 'A']
)

In [40]:
df.head()

,student_id,name,age,gender,math,english,science,classes,average,grade
0,1,student_1,15,M,90,48,69,C,69.00,C
1,2,student_2,16,M,67,37,58,B,54.00,D
2,3,student_3,16,F,73,83,54,B,70.00,C
3,4,student_4,18,M,50,76,48,B,58.00,D
4,5,student_5,16,M,36,63,97,B,65.33,C

In [43]:
#    - 'status' (Distinction / Pass / Fail using np.select)

condition = [
    df['average'] > 80,
    df['average'] >= 60,
    df['average'] < 60
]
status = ['Distinction', 'Pass', 'Fail']

df['status'] = np.select(condition, status, default = 'Unknown')
df.head()

,student_id,name,age,gender,math,english,science,classes,average,grade,status
0,1,student_1,15,M,90,48,69,C,69.00,C,Pass
1,2,student_2,16,M,67,37,58,B,54.00,D,Fail
2,3,student_3,16,F,73,83,54,B,70.00,C,Pass
3,4,student_4,18,M,50,76,48,B,58.00,D,Fail
4,5,student_5,16,M,36,63,97,B,65.33,C,Pass

In [104]:
#    - 'strongest_subject' (which of math/english/science
#       is highest for each student — hint: use df[cols].idxmax(axis=1))


subject_cols = ['math', 'english', 'science']
df['strongest_subject'] = df[subject_cols].idxmax(axis = 1) 


df.head()

,student_id,name,age,gender,math,english,science,classes,average,grade,status,strongest_subject
0,1,student_1,15,M,90,48,69,C,69.00,C,Pass,math
1,2,student_2,16,M,67,37,58,B,54.00,D,Fail,math
2,3,student_3,16,F,73,83,54,B,70.00,C,Pass,english
3,4,student_4,18,M,50,76,48,B,58.00,D,Fail,english
4,5,student_5,16,M,36,63,97,B,65.33,C,Pass,science

In [107]:
#    - 'strongest_subject' (which of math/english/science
#       is highest for each student — hint: use df[cols].idxmax(axis=1))

df[['name', 'math', 'english', 'science', 'strongest_subject']].head(10)

         name  math  english  science strongest_subject
0   student_1    90       48       69              math
1   student_2    67       37       58              math
2   student_3    73       83       54           english
3   student_4    50       76       48           english
4   student_5    36       63       97           science
5   student_6    58       59       74           science
6   student_7    36       42       75           science
7   student_8    96       76       84              math
8   student_9    99       62       30              math
9  student_10    84       64       40              math

In [51]:
# 3. CLASS COMPARISON
#    For each class (A/B/C), show:
#    - Total students

df.groupby('grade')['name'].count()

C:\Users\user\AppData\Local\Temp\ipykernel_12952\2788985555.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('grade')['name'].count()

grade
F     2
D    20
C    19
B     6
A     3
Name: name, dtype: int64

In [55]:
#    - Average score

df.groupby('grade').agg(
    count = ('average', 'count'),
    mean_avg = ('average', 'mean'),
    best_math = ('math', 'max'),
    best_english = ('english', 'max'),
    best_science = ('science', 'max'),
    worst_math = ('math', 'min'),
    worst_english = ('english', 'min'),
    worst_science = ('science', 'min')
)

C:\Users\user\AppData\Local\Temp\ipykernel_12952\1439024090.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('grade').agg(

,count,mean_avg,best_math,best_english,best_science,worst_math,worst_english,worst_science
grade,,,,,,,,
F,2,44.170000,75,40,35,47,33,35
D,20,55.484500,99,98,80,31,32,30
C,19,64.736316,99,96,97,33,48,30
B,6,75.223333,99,82,96,65,42,53
A,3,84.000000,96,78,95,87,67,80

In [111]:
#    - Pass rate (%)
# Correct — count students passing divided by total students


pass_rate = (df['average'] >= 50).sum() / len(df) * 100

print(f'over all pass rate: {pass_rate:.1f}%')

over all pass rate: 96.0%

In [119]:
df['passed'] = df['average'] >= 50

df.groupby('grade')['passed'].mean()*100

C:\Users\user\AppData\Local\Temp\ipykernel_12952\2853066899.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('grade')['passed'].mean()*100

grade
F      0.0
D    100.0
C    100.0
B    100.0
A    100.0
Name: passed, dtype: float64

In [121]:
df.groupby('grade').agg(
    total_student = ('name', 'count'),
    average_score = ('average', 'mean'),
    pass_rate = ('passed', lambda x : f'{x.mean()*100:.1f}%')
)

C:\Users\user\AppData\Local\Temp\ipykernel_12952\1132793509.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('grade').agg(

       total_student  average_score pass_rate
grade
F                  2      44.170000      0.0%
D                 20      55.484500    100.0%
C                 19      64.736316    100.0%
B                  6      75.223333    100.0%
A                  3      84.000000    100.0%

In [83]:
# 4. GENDER ANALYSIS
#    - Overall average by gender

df.groupby('gender')['average'].mean()

gender
F    63.531852
M    61.565217
Name: average, dtype: float64

In [118]:
#    - Subject-wise average by gender

df.groupby('gender')[['math', 'english', 'science']].mean()

             math    english    science
gender
F       70.925926  60.185185  59.481481
M       59.913043  65.130435  59.652174

In [91]:
#    - Who has more Distinctions by gender?

df[df['status'] == 'Distinction'].groupby('gender')['name'].count()

gender
F    2
M    1
Name: name, dtype: int64

In [92]:
df.head()

,student_id,name,age,gender,math,english,science,classes,average,grade,status
0,1,student_1,15,M,90,48,69,C,69.00,C,Pass
1,2,student_2,16,M,67,37,58,B,54.00,D,Fail
2,3,student_3,16,F,73,83,54,B,70.00,C,Pass
3,4,student_4,18,M,50,76,48,B,58.00,D,Fail
4,5,student_5,16,M,36,63,97,B,65.33,C,Pass

In [102]:
# 5. TOP AND BOTTOM PERFORMERS
#    - Top 5 students overall with their full row

df.sort_values(by = ['average'], ascending = False).head()

,student_id,name,age,gender,math,english,science,classes,average,grade,status
7,8,student_8,15,M,96,76,84,A,85.33,A,Distinction
39,40,student_40,15,F,93,67,95,B,85.00,A,Distinction
32,33,student_33,17,F,87,78,80,A,81.67,A,Distinction
42,43,student_43,15,F,99,63,77,A,79.67,B,Pass
12,13,student_13,15,M,65,82,87,B,78.00,B,Pass

In [96]:
#    - Bottom 5 students overall with their full row

df.sort_values(by = ['average'], ascending = True).head()

,student_id,name,age,gender,math,english,science,classes,average,grade,status
37,38,student_38,15,F,47,40,35,A,40.67,F,Fail
25,26,student_26,17,F,75,33,35,A,47.67,F,Fail
20,21,student_21,16,F,31,78,42,B,50.33,D,Fail
17,18,student_18,17,M,46,33,73,B,50.67,D,Fail
6,7,student_7,17,M,36,42,75,A,51.00,D,Fail

In [123]:
#    - Most improved subject overall
#      (subject with highest mean — use idxmax())

subject_mean = df[['math', 'english', 'science']].mean()
subject_mean

print(f'the subject with highest mean: {subject_mean.idxmax()} ')

the subject with highest mean: math

In [ ]:
# 6. INSIGHT SUMMARY
#    Write 4-5 sentences summarizing what you found.
#    Treat it as if you're reporting to a school principal.

# looking at the pass rate where the pass was >= 60, the pass rate is 61.74, which is a pass mark in the over all performance
# the gap between the top 5 best students and least 5 student is over 50 points score and need to be looked at to ensure improvement
# 3 of the top 5 student are females and 3 of the bottom 5 are females 
# the gap between the gender are not much so no cause for alarm
# math is the most improved subject